<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <RootNamespace>Aegis.Security.Tools</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../src/Aegis.Security.csproj" />
  </ItemGroup>
</Project>
